In [2]:
import pandas as pd
from datetime import datetime
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, fpmax, fpgrowth
from mlxtend.frequent_patterns import association_rules
from mlxtend.frequent_patterns import apriori, association_rules
from mlxtend.preprocessing import TransactionEncoder

In [3]:
path_1 = r'C:\Users\User\Desktop\Quera_Shopping_Analysis\supermarket.csv'
df_supermarket = pd.read_csv(path_1)
df_supermarket

        Customer Id        Date                Product
0      JKML5ZWXP0XQ  2020-07-20         tropical fruit
1      YOGWQIUPDAJ7  2020-04-30             whole milk
2      Q3NL22281AF6  2020-09-18              pip fruit
3      C59GRTLMZQAU  2020-12-11       other vegetables
4      WUSF8LTEQZ5L  2020-01-02             whole milk
...             ...         ...                    ...
32705  PM1BQU9H9S2Q  2019-06-05                    oil
32706  6AWIAP3ZV551  2019-08-10          sliced cheese
32707  LRWVFLSC8X5B  2019-02-23                  candy
32708  8KYRMELYKNIH  2019-04-16               cake bar
32709  41NGW85T47Q1  2019-03-12  fruit/vegetable juice

[32710 rows x 3 columns]

In [4]:
list_customer = []
for costumer in df_supermarket['Customer Id'].unique():
    list_customer.append(list(df_supermarket['Product'][df_supermarket['Customer Id'] == costumer]))
dic_customer = {}
dic_customer['product'] = list_customer

In [5]:
df_customer = pd.DataFrame(dic_customer)

In [6]:
# First Question
Number_Products = len(df_supermarket['Product'].unique())
print(Number_Products)

137

In [7]:
# Second Question
Total_Cost = len(df_supermarket['Product'])
Total_Day = len(df_supermarket['Date'].unique())
print("%.2f" % float(Total_Cost/Total_Day))

44.93

In [8]:
# Third Question
Product_Consumption = {}
for product in df_supermarket['Product'].unique():
    Product_Consumption[product] = len(df_supermarket[df_supermarket['Product'] == product])
low_four_product_list = []
for i in range(4):
    key_list = list(Product_Consumption.keys())
    val_list = list(Product_Consumption.values())
    low_four_product_list.append(key_list[val_list.index(min(val_list))])
    del(Product_Consumption[key_list[val_list.index(min(val_list))]])
for element in low_four_product_list:
    if element != low_four_product_list[-1]:
        print(element,end=',')
    else:
        print(element)

kitchen utensil,preservation products,baby cosmetics,bags

In [9]:
Basket_Customer = {}
for customer in df_supermarket['Customer Id'].unique():
    number = list(df_supermarket['Date'][df_supermarket['Customer Id'] == customer])
    date = []
    for element in number:
        if element[0:4] == '2020':
            date.append(element)
    set_date = set(date)      
    Basket_Customer[customer] = len(set_date)
list(Basket_Customer.items())[0:5]

[('JKML5ZWXP0XQ', 2),
 ('YOGWQIUPDAJ7', 1),
 ('Q3NL22281AF6', 3),
 ('C59GRTLMZQAU', 1),
 ('WUSF8LTEQZ5L', 1)]

In [10]:
# Fourth Question  
Five_Most_Basket_Customer = []
for i in range(5):
    key_list = list(Basket_Customer.keys())
    val_list = list(Basket_Customer.values())
    Five_Most_Basket_Customer.append(key_list[val_list.index(max(val_list))])
    del(Basket_Customer[key_list[val_list.index(max(val_list))]])
for element in Five_Most_Basket_Customer:
    if element != Five_Most_Basket_Customer[-1]:
        print(element,end=',')
    else:
        print(element)

QBUS9NZY39BE,M2DT2Z00NQCH,M722MPITBY07,0ZRF32AJ06BC,E7FD9BU4OK0F

In [11]:
df_supermarket['Date_changed'] = df_supermarket['Date']
df_supermarket['Date_changed'].astype('str')
df_supermarket['Date_changed'] = df_supermarket['Date_changed'].str.replace('-','')
df_supermarket['Date_changed'] = df_supermarket['Date_changed'].astype('str')
df_supermarket

        Customer Id        Date                Product Date_changed
0      JKML5ZWXP0XQ  2020-07-20         tropical fruit     20200720
1      YOGWQIUPDAJ7  2020-04-30             whole milk     20200430
2      Q3NL22281AF6  2020-09-18              pip fruit     20200918
3      C59GRTLMZQAU  2020-12-11       other vegetables     20201211
4      WUSF8LTEQZ5L  2020-01-02             whole milk     20200102
...             ...         ...                    ...          ...
32705  PM1BQU9H9S2Q  2019-06-05                    oil     20190605
32706  6AWIAP3ZV551  2019-08-10          sliced cheese     20190810
32707  LRWVFLSC8X5B  2019-02-23                  candy     20190223
32708  8KYRMELYKNIH  2019-04-16               cake bar     20190416
32709  41NGW85T47Q1  2019-03-12  fruit/vegetable juice     20190312

[32710 rows x 4 columns]

In [12]:
# Fifth Question
weekDays = ("Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday")
Day_list = []
for date in df_supermarket['Date_changed']:
    Day = weekDays[datetime(int(date[0:4]),int(date[4:6]),int(date[6:8])).weekday()]
    Day_list.append(Day)
df_supermarket['Weekday'] = Day_list
df_supermarket['Weekday'].value_counts().idxmax()

'Wednesday'

In [13]:
df_supermarket = pd.get_dummies(df_supermarket,columns = ['Product'])
df_supermarket.columns = df_supermarket.columns.str.replace("Product_", "")
Product_List = []
for column in df_supermarket.columns:
    if column != 'Customer Id' and column != 'Date' and column != 'Date_changed' and column != 'Weekday':
        Product_List.append(column)
Product_List

['Instant food products',
 'UHT-milk',
 'abrasive cleaner',
 'artif. sweetener',
 'baby cosmetics',
 'bags',
 'baking powder',
 'bathroom cleaner',
 'beef',
 'berries',
 'beverages',
 'bottled beer',
 'bottled water',
 'brown bread',
 'butter',
 'butter milk',
 'cake bar',
 'candles',
 'candy',
 'canned fish',
 'canned fruit',
 'canned vegetables',
 'cereals',
 'chewing gum',
 'chicken',
 'chocolate',
 'chocolate marshmallow',
 'citrus fruit',
 'cleaner',
 'cocoa drinks',
 'coffee',
 'condensed milk',
 'cooking chocolate',
 'cookware',
 'cream',
 'curd',
 'curd cheese',
 'decalcifier',
 'dental care',
 'dessert',
 'detergent',
 'dish cleaner',
 'dishes',
 'domestic eggs',
 'finished products',
 'fish',
 'flour',
 'flower (seeds)',
 'flower soil/fertilizer',
 'frozen chicken',
 'frozen dessert',
 'frozen fish',
 'frozen fruits',
 'frozen meals',
 'frozen potato products',
 'frozen vegetables',
 'fruit/vegetable juice',
 'grapes',
 'hamburger meat',
 'hard cheese',
 'herbs',
 'honey',
 'house keeping products',
 'hygiene articles',
 'ice cream',
 'instant coffee',
 'jam',
 'ketchup',
 'kitchen towels',
 'kitchen utensil',
 'light bulbs',
 'long life bakery product',
 'make up remover',
 'male cosmetics',
 'margarine',
 'mayonnaise',
 'meat',
 'meat spreads',
 'mustard',
 'napkins',
 'nut snack',
 'nuts/prunes',
 'oil',
 'onions',
 'organic products',
 'organic sausage',
 'other vegetables',
 'packaged fruit/vegetables',
 'pasta',
 'pastry',
 'pickled vegetables',
 'pip fruit',
 'popcorn',
 'pot plants',
 'potato products',
 'preservation products',
 'processed cheese',
 'pudding powder',
 'ready soups',
 'rice',
 'roll products',
 'rolls/buns',
 'root vegetables',
 'salad dressing',
 'salt',
 'salty snack',
 'sauces',
 'sausage',
 'seasonal products',
 'semi-finished bread',
 'skin care',
 'sliced cheese',
 'snack products',
 'soap',
 'soda',
 'soft cheese',
 'softener',
 'soups',
 'specialty bar',
 'specialty cheese',
 'specialty chocolate',
 'specialty fat',
 'specialty vegetables',
 'spices',
 'spread cheese',
 'sugar',
 'sweet spreads',
 'tea',
 'toilet cleaner',
 'tropical fruit',
 'turkey',
 'waffles',
 'whipped/sour cream',
 'white bread',
 'whole milk',
 'yogurt',
 'zwieback']

In [14]:
a = TransactionEncoder()
a_data = a.fit(list_customer).transform(list_customer)
df = pd.DataFrame(a_data,columns=a.columns_)
df = df.replace(False,0)
df = df.replace(True,1)
df

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,bags,baking powder,bathroom cleaner,beef,berries,...,tea,toilet cleaner,tropical fruit,turkey,waffles,whipped/sour cream,white bread,whole milk,yogurt,zwieback
0,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3888,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3889,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3890,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3891,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3892,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
df = apriori(df, min_support = 0.01, use_colnames = True, verbose = 1)
df

c:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:111: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

Processing 1255 combinations | Sampling itemset size 54

       support                                           itemsets
0     0.015412                            (Instant food products)
1     0.078603                                         (UHT-milk)
2     0.031081                                    (baking powder)
3     0.119702                                             (beef)
4     0.079887                                          (berries)
...        ...                                                ...
2152  0.014899         (whole milk, tropical fruit, soda, yogurt)
2153  0.011045     (whole milk, soda, yogurt, whipped/sour cream)
2154  0.010532  (bottled water, yogurt, rolls/buns, whole milk...
2155  0.013614  (yogurt, sausage, rolls/buns, whole milk, othe...
2156  0.013614  (yogurt, soda, rolls/buns, whole milk, other v...

[2157 rows x 2 columns]

In [16]:
# Sixth Question
support = {}
for row in df.index:
    support[df['itemsets'][row]] = df['support'][row]
Five_Most_Support = []
for i in range(5):
    key_list = list(support.keys())
    val_list = list(support.values())
    Five_Most_Support.append(key_list[val_list.index(max(val_list))])
    del(support[key_list[val_list.index(max(val_list))]])
for element in Five_Most_Support:
    if element != Five_Most_Support[-1]:
        print(element,end=',')
    else:
        print(element)

frozenset({'whole milk'}),frozenset({'other vegetables'}),frozenset({'rolls/buns'}),frozenset({'soda'}),frozenset({'yogurt'})

In [21]:
df_ar = association_rules(df, metric = "confidence", min_threshold = 0.7)
df_ar

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,"(chocolate, fruit/vegetable juice)",(whole milk),0.014385,0.458772,0.010789,0.750000,1.634798,0.004189,2.164911
1,"(domestic eggs, meat)",(whole milk),0.013100,0.458772,0.010275,0.784314,1.709593,0.004265,2.509329
2,"(pip fruit, hamburger meat)",(whole milk),0.016440,0.458772,0.011559,0.703125,1.532624,0.004017,1.823083
3,"(yogurt, rolls/buns, bottled beer)",(whole milk),0.019265,0.458772,0.013871,0.720000,1.569406,0.005033,1.932957
4,"(bottled water, brown bread, other vegetables)",(whole milk),0.016697,0.458772,0.012073,0.723077,1.576113,0.004413,1.954434
5,"(bottled water, pip fruit, yogurt)",(whole milk),0.013871,0.458772,0.010275,0.740741,1.614616,0.003911,2.087593
6,"(brown bread, yogurt, rolls/buns)",(whole milk),0.017467,0.458772,0.012844,0.735294,1.602744,0.004830,2.044639
7,"(other vegetables, yogurt, butter)",(whole milk),0.022348,0.458772,0.015669,0.701149,1.528317,0.005417,1.811032
8,"(soda, curd, yogurt)",(whole milk),0.015155,0.458772,0.010789,0.711864,1.551673,0.003836,1.878379
9,"(domestic eggs, sausage, rolls/buns)",(whole milk),0.014899,0.458772,0.010532,0.706897,1.540844,0.003697,1.846542
10,"(pip fruit, pastry, yogurt)",(whole milk),0.014899,0.458772,0.010532,0.706897,1.540844,0.003697,1.846542
11,"(bottled water, other vegetables, yogurt, roll...",(whole milk),0.014128,0.458772,0.010532,0.745455,1.624891,0.004050,2.126252

In [18]:
# Seventh Question
confidence = {}
for row_2 in df_ar.index:
    confidence[str(df_ar['antecedents'][row_2]) + str('->') + str(df_ar['consequents'][row_2])] = df_ar['confidence'][row_2]
Two_Most_Confidence = []
for i in range(2):
    key_list = list(confidence.keys())
    val_list = list(confidence.values())
    Two_Most_Confidence.append(key_list[val_list.index(max(val_list))])
    del(confidence[key_list[val_list.index(max(val_list))]])
for element in Two_Most_Confidence:
    if element != Two_Most_Confidence[-1]:
        print(element,end='|')
    else:
        print(element)

frozenset({'domestic eggs', 'meat'})->frozenset({'whole milk'})|frozenset({'chocolate', 'fruit/vegetable juice'})->frozenset({'whole milk'})